### ISSUE TITLE
gulp 4 options throwing a console error but still runs

### ISSUE THREAD

**Issue by HansUXdev** [zurb/octophant#10]
I've been having issues using octophant in the standard zurb template ever since you switched to gulp 4

```
function settings() {
    octophant('src/assets/scss/components/**/*.scss', {
      title: 'Component Settings',
      output: 'src/assets/scss/settings/_components.scss'
    });
}
```

The task runs but the Console logs

```
The following tasks did not complete: build, settings
Did you forget to signal async completion?

```

**Comment by ghost** [comment]
If Your read the docs of gulp 4 there have been come changes ... but here is a good example

> In Gulp 3, if the code you ran inside a task function was synchronous, there was nothing special that needed to be done. That’s changed in Gulp 4: now you need to use the done callback (which I’ll get to shortly). Also, for asynchronous tasks, you had 3 options for making sure Gulp was able to recognize when your task finished, which were:

see more in this [Gulp 4 Tutorial](https://www.joezimjs.com/javascript/complete-guide-upgrading-gulp-4/)

But as for you example to get rid of the error you simply need to return the stream,

```
function settings() {
   return octophant('src/assets/scss/components/**/*.scss', {
      title: 'Component Settings',
      output: 'src/assets/scss/settings/_components.scss'
    });
}
```

I also note that you do not have the callback that octophant requires in my version if different

so my final task looks a little like

```
function settings(callback) {
   return octophant(
                   'src/assets/scss/components/**/*.scss',
                   {
                     title: 'Component Settings',
                     output: 'src/assets/scss/settings/_components.scss'
                   },
                   callback());
}
```
